 $(function(){
       
            //首页顶部top_bottom开始
            $(".top_bottom a").hover(
                    function(){
                        $(this).css("color","#999999");
                    },
                    function(){
                        $(this).css("color","black");
                    }
            )
            $("#top_bottom_li4").hover(
                    function(){
                        $("#top_bottom_xf").show();
                    },
                    function(){
                        $("#top_bottom_xf").hide();
                    }
            )
            $("#top_bottom_li5").hover(
                    function(){
                        $("#top_bottom_xf1").show();
                    },
                    function(){
                        $("#top_bottom_xf1").hide();
                    }
            )
              $("#top_bottom_xf").hover(
                    function(){
                        $(this).show();
                    },
                    function(){
                        $(this).hide();
                    }
            )
            $("#top_bottom_xf1").hover(
                    function(){
                        $(this).show();
                    },
                    function(){
                        $(this).hide();
                    }
            )
            //首页顶部top_bottom结束
        })